name: 'pr-first-comment'
description: 'GitHub Action for posting first comment to pull request'
inputs:
  token:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: true
runs:
  using: 'node12'
  main: 'index.js'
