name: release

on:
  release:
    types:
      - published

jobs:
  move-major-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Move major version tag
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            # Generate tag from release ref
            const majorTag = context.ref.split('/')[2].split('.')[0];

            # Delete current tag
            try {
                await github.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `tags/${ majorTag }`
                })
            } catch (e) {
              console.log("The tag doesn't exist yet: " + e)
            }

            # Create tag with new release
            await github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${ majorTag }`,
              sha: context.sha
            });
